# Generated by Django 3.1.3 on 2021-08-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addnote', '0003_note_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_cnt', models.IntegerField(default=0)),
                ('input_date', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
