# Generated by Django 3.2.6 on 2021-08-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addnote', '0004_auto_20210819_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notecnt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
